# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalproject.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(502, 501)
        Form.setMinimumSize(QtCore.QSize(502, 501))
        Form.setMaximumSize(QtCore.QSize(502, 501))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pic/beeremo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.drinkordrunk = QtWidgets.QStackedWidget(Form)
        self.drinkordrunk.setGeometry(QtCore.QRect(0, 0, 501, 511))
        self.drinkordrunk.setObjectName("drinkordrunk")
##what
        self.what = QtWidgets.QWidget()
        self.what.setObjectName("what")
        self.label_2 = QtWidgets.QLabel(self.what)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 501, 491))
        self.label_2.setMinimumSize(QtCore.QSize(461, 401))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../pic/IMG_1373[7167].jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.specialevent = QtWidgets.QPushButton(self.what)
        self.specialevent.setGeometry(QtCore.QRect(40, 140, 221, 51))
        self.specialevent.setStyleSheet("QPushButton{\n"
"font: 18pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.specialevent.setObjectName("specialevent")
        self.booking = QtWidgets.QPushButton(self.what)
        self.booking.setGeometry(QtCore.QRect(290, 140, 141, 51))
        self.booking.setStyleSheet("QPushButton{\n"
"font: 18pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"")
        self.booking.setObjectName("booking")
        self.menunorder = QtWidgets.QPushButton(self.what)
        self.menunorder.setGeometry(QtCore.QRect(40, 230, 211, 51))
        self.menunorder.setStyleSheet("QPushButton{\n"
"font: 18pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"")
        self.menunorder.setObjectName("menunorder")
        self.paying = QtWidgets.QPushButton(self.what)
        self.paying.setGeometry(QtCore.QRect(290, 230, 141, 51))
        self.paying.setStyleSheet("QPushButton{\n"
"font: 18pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.paying.setObjectName("paying")
        self.map = QtWidgets.QPushButton(self.what)
        self.map.setGeometry(QtCore.QRect(70, 310, 141, 51))
        self.map.setStyleSheet("QPushButton{\n"
"font: 18pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.map.setObjectName("map")
        self.contactus = QtWidgets.QPushButton(self.what)
        self.contactus.setGeometry(QtCore.QRect(270, 310, 181, 51))
        self.contactus.setStyleSheet("QPushButton{\n"
"font: 18pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.contactus.setObjectName("contactus")
        self.finish1 = QtWidgets.QPushButton(self.what)
        self.finish1.setGeometry(QtCore.QRect(180, 390, 131, 51))
        self.finish1.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.finish1.setObjectName("finish1")
        self.drinkordrunk.addWidget(self.what)
        self.specialeventpage = QtWidgets.QWidget()
        self.specialeventpage.setObjectName("specialeventpage")
        self.label_3 = QtWidgets.QLabel(self.specialeventpage)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 501, 491))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../pic/IMG_1375[7175].jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.backspecial = QtWidgets.QPushButton(self.specialeventpage)
        self.backspecial.setGeometry(QtCore.QRect(210, 430, 111, 41))
        self.backspecial.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backspecial.setObjectName("backspecial")
        self.drinkordrunk.addWidget(self.specialeventpage)
        self.bookingpage = QtWidgets.QWidget()
        self.bookingpage.setObjectName("bookingpage")
        self.label_4 = QtWidgets.QLabel(self.bookingpage)
        self.label_4.setGeometry(QtCore.QRect(0, -10, 501, 521))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../pic/IMG_1388[7195].jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QTextEdit(self.bookingpage)
        self.name.setGeometry(QtCore.QRect(240, 170, 181, 21))
        self.name.setObjectName("name")
        self.email = QtWidgets.QTextEdit(self.bookingpage)
        self.email.setGeometry(QtCore.QRect(240, 230, 181, 21))
        self.email.setObjectName("email")
        self.tel = QtWidgets.QTextEdit(self.bookingpage)
        self.tel.setGeometry(QtCore.QRect(240, 310, 181, 21))
        self.tel.setObjectName("tel")
        self.guest = QtWidgets.QTextEdit(self.bookingpage)
        self.guest.setGeometry(QtCore.QRect(240, 390, 181, 21))
        self.guest.setObjectName("guest")
        self.date = QtWidgets.QTextEdit(self.bookingpage)
        self.date.setGeometry(QtCore.QRect(240, 450, 181, 21))
        self.date.setObjectName("date")
        self.backbooking = QtWidgets.QPushButton(self.bookingpage)
        self.backbooking.setGeometry(QtCore.QRect(390, 476, 101, 20))
        self.backbooking.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backbooking.setObjectName("backbooking")
        self.drinkordrunk.addWidget(self.bookingpage)
        self.orderpage = QtWidgets.QWidget()
        self.orderpage.setObjectName("orderpage")
        self.label_5 = QtWidgets.QLabel(self.orderpage)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../pic/IMG_1391[7210].jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.minus1 = QtWidgets.QPushButton(self.orderpage)
        self.minus1.setGeometry(QtCore.QRect(70, 180, 16, 16))
        self.minus1.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus1.setObjectName("minus1")
        self.minus4 = QtWidgets.QPushButton(self.orderpage)
        self.minus4.setGeometry(QtCore.QRect(180, 310, 16, 16))
        self.minus4.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus4.setObjectName("minus4")
        self.minus3 = QtWidgets.QPushButton(self.orderpage)
        self.minus3.setGeometry(QtCore.QRect(70, 310, 16, 16))
        self.minus3.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus3.setObjectName("minus3")
        self.minus2 = QtWidgets.QPushButton(self.orderpage)
        self.minus2.setGeometry(QtCore.QRect(180, 180, 16, 16))
        self.minus2.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus2.setObjectName("minus2")
        self.plus4 = QtWidgets.QPushButton(self.orderpage)
        self.plus4.setGeometry(QtCore.QRect(150, 310, 16, 16))
        self.plus4.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus4.setObjectName("plus4")
        self.plus5 = QtWidgets.QPushButton(self.orderpage)
        self.plus5.setGeometry(QtCore.QRect(50, 450, 16, 16))
        self.plus5.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus5.setObjectName("plus5")
        self.plus1 = QtWidgets.QPushButton(self.orderpage)
        self.plus1.setGeometry(QtCore.QRect(50, 180, 16, 16))
        self.plus1.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus1.setObjectName("plus1")
        self.plus6 = QtWidgets.QPushButton(self.orderpage)
        self.plus6.setGeometry(QtCore.QRect(150, 450, 16, 16))
        self.plus6.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus6.setObjectName("plus6")
        self.backorder = QtWidgets.QPushButton(self.orderpage)
        self.backorder.setGeometry(QtCore.QRect(250, 440, 101, 41))
        self.backorder.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backorder.setObjectName("backorder")
        self.plus3 = QtWidgets.QPushButton(self.orderpage)
        self.plus3.setGeometry(QtCore.QRect(50, 310, 16, 16))
        self.plus3.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus3.setObjectName("plus3")
        self.minus6 = QtWidgets.QPushButton(self.orderpage)
        self.minus6.setGeometry(QtCore.QRect(180, 450, 16, 16))
        self.minus6.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus6.setObjectName("minus6")
        self.minus5 = QtWidgets.QPushButton(self.orderpage)
        self.minus5.setGeometry(QtCore.QRect(70, 450, 16, 16))
        self.minus5.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus5.setObjectName("minus5")
        self.showtotal = QtWidgets.QLabel(self.orderpage)
        self.showtotal.setGeometry(QtCore.QRect(270, 400, 201, 21))
        self.showtotal.setStyleSheet("font: 18pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.showtotal.setText("")
        self.showtotal.setObjectName("showtotal")
        self.plus2 = QtWidgets.QPushButton(self.orderpage)
        self.plus2.setGeometry(QtCore.QRect(150, 180, 16, 16))
        self.plus2.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus2.setObjectName("plus2")
        self.payingorder = QtWidgets.QPushButton(self.orderpage)
        self.payingorder.setGeometry(QtCore.QRect(360, 440, 121, 41))
        self.payingorder.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.payingorder.setObjectName("payingorder")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.orderpage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 140, 160, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.as200 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.as200.setStyleSheet("font: 18pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.as200.setText("")
        self.as200.setObjectName("as200")
        self.verticalLayout.addWidget(self.as200)
        self.bm300 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bm300.setStyleSheet("font: 18pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.bm300.setText("")
        self.bm300.setObjectName("bm300")
        self.verticalLayout.addWidget(self.bm300)
        self.b52 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.b52.setStyleSheet("font: 18pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.b52.setText("")
        self.b52.setObjectName("b52")
        self.verticalLayout.addWidget(self.b52)
        self.beer = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.beer.setStyleSheet("font: 18pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.beer.setText("")
        self.beer.setObjectName("beer")
        self.verticalLayout.addWidget(self.beer)
        self.tq = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tq.setStyleSheet("font: 18pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.tq.setText("")
        self.tq.setObjectName("tq")
        self.verticalLayout.addWidget(self.tq)
        self.regen = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.regen.setStyleSheet("font: 18pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.regen.setText("")
        self.regen.setObjectName("regen")
        self.verticalLayout.addWidget(self.regen)
        self.drinkordrunk.addWidget(self.orderpage)
        self.payingpage = QtWidgets.QWidget()
        self.payingpage.setObjectName("payingpage")
        self.label_6 = QtWidgets.QLabel(self.payingpage)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../pic/IMG_1390[7206].jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.backpaying = QtWidgets.QPushButton(self.payingpage)
        self.backpaying.setGeometry(QtCore.QRect(10, 420, 101, 51))
        self.backpaying.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backpaying.setObjectName("backpaying")
        self.finish2 = QtWidgets.QPushButton(self.payingpage)
        self.finish2.setGeometry(QtCore.QRect(390, 420, 101, 51))
        self.finish2.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}\n"
"")
        self.finish2.setObjectName("finish2")
        self.drinkordrunk.addWidget(self.payingpage)
        self.contactpage = QtWidgets.QWidget()
        self.contactpage.setObjectName("contactpage")
        self.label_7 = QtWidgets.QLabel(self.contactpage)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../pic/ct.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.backcontact = QtWidgets.QPushButton(self.contactpage)
        self.backcontact.setGeometry(QtCore.QRect(190, 430, 121, 41))
        self.backcontact.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 18px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backcontact.setObjectName("backcontact")
        self.drinkordrunk.addWidget(self.contactpage)
        self.firstpage = QtWidgets.QWidget()
        self.firstpage.setObjectName("firstpage")
        self.label = QtWidgets.QLabel(self.firstpage)
        self.label.setGeometry(QtCore.QRect(-10, 0, 521, 511))
        self.label.setMaximumSize(QtCore.QSize(1024, 768))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pic/IMG_1377[7179].jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(self.firstpage)
        self.start.setGeometry(QtCore.QRect(170, 380, 151, 41))
        self.start.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.start.setObjectName("start")
        self.drinkordrunk.addWidget(self.firstpage)

        self.retranslateUi(Form)
        self.drinkordrunk.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)
##code
        


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DRINK OR DRUNK"))
        self.specialevent.setText(_translate("Form", " SPECIAL EVENT"))
        self.booking.setText(_translate("Form", "BOOKING"))
        self.menunorder.setText(_translate("Form", "MENU n ORDER"))
        self.paying.setText(_translate("Form", "PAYING"))
        self.map.setText(_translate("Form", "MAP"))
        self.contactus.setText(_translate("Form", "CONTACT US"))
        self.finish1.setText(_translate("Form", "FINISH"))
        self.backspecial.setText(_translate("Form", "BACK"))
        self.backbooking.setText(_translate("Form", "DONE"))
        self.minus1.setText(_translate("Form", "-"))
        self.minus4.setText(_translate("Form", "-"))
        self.minus3.setText(_translate("Form", "-"))
        self.minus2.setText(_translate("Form", "-"))
        self.plus4.setText(_translate("Form", "+"))
        self.plus5.setText(_translate("Form", "+"))
        self.plus1.setText(_translate("Form", "+"))
        self.plus6.setText(_translate("Form", "+"))
        self.backorder.setText(_translate("Form", "BACK"))
        self.plus3.setText(_translate("Form", "+"))
        self.minus6.setText(_translate("Form", "-"))
        self.minus5.setText(_translate("Form", "-"))
        self.plus2.setText(_translate("Form", "+"))
        self.payingorder.setText(_translate("Form", "PAYING"))
        self.backpaying.setText(_translate("Form", "BACK"))
        self.finish2.setText(_translate("Form", "FINISH"))
        self.backcontact.setText(_translate("Form", "BACK"))
        self.start.setText(_translate("Form", "START"))
        
        self.start = self.findChild(QtWidgets.QPushButton,'start')
        
        self.start.clicked.connect(self.goto2)
    def goto2(self):
        self.ui.QtWidget.setCurrentindex(5)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
