# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '63011170pj.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_Form(object):
###create global
    global basket
    basket = 0
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(502, 501)
        Form.setMinimumSize(QtCore.QSize(502, 501))
        Form.setMaximumSize(QtCore.QSize(502, 501))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pic/beeremo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 501, 511))
        self.stackedWidget.setObjectName("stackedWidget")
##what r u looking 4
        self.what = QtWidgets.QWidget()
        self.what.setObjectName("what")
        self.label_2 = QtWidgets.QLabel(self.what)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_2.setMinimumSize(QtCore.QSize(461, 401))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../pic/IMG_1373[7167].jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2") 
        self.specialevent = QtWidgets.QPushButton(self.what)
        self.specialevent.setGeometry(QtCore.QRect(40, 140, 221, 51))
        self.specialevent.setStyleSheet("QPushButton{\n"
"font: 10pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 24px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.specialevent.setObjectName("specialevent")
        self.booking = QtWidgets.QPushButton(self.what)
        self.booking.setGeometry(QtCore.QRect(290, 140, 141, 51))
        self.booking.setStyleSheet("QPushButton{\n"
"font: 10pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 24px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"")
        self.booking.setObjectName("booking")
        self.menunorder = QtWidgets.QPushButton(self.what)
        self.menunorder.setGeometry(QtCore.QRect(40, 230, 211, 51))
        self.menunorder.setStyleSheet("QPushButton{\n"
"font: 10pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 24px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.menunorder.setObjectName("menunorder")
        self.paying = QtWidgets.QPushButton(self.what)
        self.paying.setGeometry(QtCore.QRect(290, 230, 141, 51))
        self.paying.setStyleSheet("QPushButton{\n"
"font: 10pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 24px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.paying.setObjectName("paying")
        self.map = QtWidgets.QPushButton(self.what)
        self.map.setGeometry(QtCore.QRect(80, 310, 131, 51))
        self.map.setStyleSheet("QPushButton{\n"
"font: 10pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 24px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.map.setObjectName("map")
        self.contactus = QtWidgets.QPushButton(self.what)
        self.contactus.setGeometry(QtCore.QRect(270, 310, 181, 51))
        self.contactus.setStyleSheet("QPushButton{\n"
"font: 10pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 24px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.contactus.setObjectName("contactus")
        self.finish1 = QtWidgets.QPushButton(self.what)
        self.finish1.setGeometry(QtCore.QRect(180, 390, 131, 51))
        self.finish1.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 24px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.finish1.setObjectName("finish1")
        self.stackedWidget.addWidget(self.what)
        self.specialeventpage = QtWidgets.QWidget()
        self.specialeventpage.setObjectName("specialeventpage")
        self.label_3 = QtWidgets.QLabel(self.specialeventpage)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../pic/IMG_1375[7175].jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.backspecial = QtWidgets.QPushButton(self.specialeventpage)
        self.backspecial.setGeometry(QtCore.QRect(210, 450, 111, 41))
        self.backspecial.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backspecial.setObjectName("backspecial")
        self.stackedWidget.addWidget(self.specialeventpage)
        
###booking
        
        self.bookingpage = QtWidgets.QWidget()
        self.bookingpage.setObjectName("bookingpage")
        self.label_4 = QtWidgets.QLabel(self.bookingpage)
        self.label_4.setGeometry(QtCore.QRect(0, -20, 501, 521))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../pic/IMG_1388[7195].jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QTextEdit(self.bookingpage)
        self.name.setGeometry(QtCore.QRect(240, 150, 181, 31))
        self.name.setObjectName("name")
        self.email = QtWidgets.QTextEdit(self.bookingpage)
        self.email.setGeometry(QtCore.QRect(240, 220, 181, 31))
        self.email.setObjectName("email")
        self.tel = QtWidgets.QTextEdit(self.bookingpage)
        self.tel.setGeometry(QtCore.QRect(240, 290, 181, 31))
        self.tel.setObjectName("tel")
        self.guest = QtWidgets.QTextEdit(self.bookingpage)
        self.guest.setGeometry(QtCore.QRect(240, 370, 181, 31))
        self.guest.setObjectName("guest")
        self.date = QtWidgets.QTextEdit(self.bookingpage)
        self.date.setGeometry(QtCore.QRect(240, 430, 181, 31))
        self.date.setObjectName("date")
        self.summit = QtWidgets.QPushButton(self.bookingpage)
        self.summit.setGeometry(QtCore.QRect(380, 470, 111, 21))
        self.summit.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"\n"
"    color: rgb(255, 210, 201);\n"
"font: 11pt \"Elephant\";\n"
"    background-color: rgb(170, 0, 0);\n"
"border-radius: 8px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 221, 203);\n"
"    color:rgb(170, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.summit.setObjectName("summit")
        self.backbooking = QtWidgets.QPushButton(self.bookingpage)
        self.backbooking.setGeometry(QtCore.QRect(240, 470, 111, 21))
        self.backbooking.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 8px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backbooking.setObjectName("backbooking")
        self.stackedWidget.addWidget(self.bookingpage)

###order
        self.orderpage = QtWidgets.QWidget()
        self.orderpage.setObjectName("orderpage")
        self.label_5 = QtWidgets.QLabel(self.orderpage)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../pic/IMG_1391[7210].jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.minus1 = QtWidgets.QPushButton(self.orderpage)
        self.minus1.setGeometry(QtCore.QRect(70, 170, 31, 31))
        self.minus1.setStyleSheet("QPushButton{\n"
"font: 14pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus1.setObjectName("minus1")
        self.minus4 = QtWidgets.QPushButton(self.orderpage)
        self.minus4.setGeometry(QtCore.QRect(180, 310, 31, 31))
        self.minus4.setStyleSheet("QPushButton{\n"
"font: 14pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus4.setObjectName("minus4")
        self.minus3 = QtWidgets.QPushButton(self.orderpage)
        self.minus3.setGeometry(QtCore.QRect(70, 300, 31, 31))
        self.minus3.setStyleSheet("QPushButton{\n"
"font: 14pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus3.setObjectName("minus3")
        self.minus2 = QtWidgets.QPushButton(self.orderpage)
        self.minus2.setGeometry(QtCore.QRect(170, 170, 31, 31))
        self.minus2.setStyleSheet("QPushButton{\n"
"font: 14pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus2.setObjectName("minus2")
        self.plus4 = QtWidgets.QPushButton(self.orderpage)
        self.plus4.setGeometry(QtCore.QRect(150, 310, 31, 31))
        self.plus4.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus4.setObjectName("plus4")
        self.plus5 = QtWidgets.QPushButton(self.orderpage)
        self.plus5.setGeometry(QtCore.QRect(40, 435, 31, 31))
        self.plus5.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus5.setObjectName("plus5")
        self.plus1 = QtWidgets.QPushButton(self.orderpage)
        self.plus1.setGeometry(QtCore.QRect(40, 170, 31, 31))
        self.plus1.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus1.setObjectName("plus1")
        self.plus6 = QtWidgets.QPushButton(self.orderpage)
        self.plus6.setGeometry(QtCore.QRect(150, 435, 31, 31))
        self.plus6.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus6.setObjectName("plus6")
        self.backorder = QtWidgets.QPushButton(self.orderpage)
        self.backorder.setGeometry(QtCore.QRect(250, 440, 101, 41))
        self.backorder.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backorder.setObjectName("backorder")
        self.plus3 = QtWidgets.QPushButton(self.orderpage)
        self.plus3.setGeometry(QtCore.QRect(40, 300, 31, 31))
        self.plus3.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus3.setObjectName("plus3")
        self.minus6 = QtWidgets.QPushButton(self.orderpage)
        self.minus6.setGeometry(QtCore.QRect(180, 435, 31, 31))
        self.minus6.setStyleSheet("QPushButton{\n"
"font: 14pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus6.setObjectName("minus6")
        self.minus5 = QtWidgets.QPushButton(self.orderpage)
        self.minus5.setGeometry(QtCore.QRect(70, 435, 31, 31))
        self.minus5.setStyleSheet("QPushButton{\n"
"font: 14pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus5.setObjectName("minus5")
        self.showtotal = QtWidgets.QLabel(self.orderpage)
        self.showtotal.setGeometry(QtCore.QRect(270, 400, 221, 31))
        self.showtotal.setStyleSheet("font: 14pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.showtotal.setText("")
        self.showtotal.setObjectName("showtotal")
        self.plus2 = QtWidgets.QPushButton(self.orderpage)
        self.plus2.setGeometry(QtCore.QRect(140, 170, 31, 31))
        self.plus2.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus2.setObjectName("plus2")
        self.payingorder = QtWidgets.QPushButton(self.orderpage)
        self.payingorder.setGeometry(QtCore.QRect(360, 440, 121, 41))
        self.payingorder.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.payingorder.setObjectName("payingorder")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.orderpage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 90, 221, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.as200 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.as200.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.as200.setText("")
        self.as200.setObjectName("as200")
        self.verticalLayout.addWidget(self.as200)
        self.bm300 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bm300.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.bm300.setText("")
        self.bm300.setObjectName("bm300")
        self.verticalLayout.addWidget(self.bm300)
        self.b52 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.b52.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.b52.setText("")
        self.b52.setObjectName("b52")
        self.verticalLayout.addWidget(self.b52)
        self.beer = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.beer.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.beer.setText("")
        self.beer.setObjectName("beer")
        self.verticalLayout.addWidget(self.beer)
        self.tq = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tq.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.tq.setText("")
        self.tq.setObjectName("tq")
        self.verticalLayout.addWidget(self.tq)
        self.regen = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.regen.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.regen.setText("")
        self.regen.setObjectName("regen")
        self.verticalLayout.addWidget(self.regen)
        self.stackedWidget.addWidget(self.orderpage)

####paying

        self.payingpage = QtWidgets.QWidget()
        self.payingpage.setObjectName("payingpage")
        self.label_6 = QtWidgets.QLabel(self.payingpage)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../pic/IMG_1390[7206].jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.backpaying = QtWidgets.QPushButton(self.payingpage)
        self.backpaying.setGeometry(QtCore.QRect(20, 440, 101, 31))
        self.backpaying.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 14px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backpaying.setObjectName("backpaying")
        self.finish2 = QtWidgets.QPushButton(self.payingpage)
        self.finish2.setGeometry(QtCore.QRect(380, 440, 111, 31))
        self.finish2.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 14px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}\n"
"")
        self.finish2.setObjectName("finish2")
        self.stackedWidget.addWidget(self.payingpage)

####contact
        self.contactpage = QtWidgets.QWidget()
        self.contactpage.setObjectName("contactpage")
        self.label_7 = QtWidgets.QLabel(self.contactpage)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../pic/ct.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.backcontact = QtWidgets.QPushButton(self.contactpage)
        self.backcontact.setGeometry(QtCore.QRect(190, 420, 131, 51))
        self.backcontact.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"border-radius: 24px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backcontact.setObjectName("backcontact")
        self.stackedWidget.addWidget(self.contactpage)
        self.firstpage = QtWidgets.QWidget()

####firstpage

        self.firstpage.setObjectName("firstpage")
        self.label = QtWidgets.QLabel(self.firstpage)
        self.label.setGeometry(QtCore.QRect(-10, 0, 521, 511))
        self.label.setMaximumSize(QtCore.QSize(1024, 768))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pic/IMG_1377[7179].jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(self.firstpage)
        self.start.setGeometry(QtCore.QRect(170, 380, 151, 41))
        self.start.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Elephant\";\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.start.setObjectName("start")
        self.stackedWidget.addWidget(self.firstpage)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)

######
##code
        self.start.clicked.connect(self.gowhat)
        self.specialevent.clicked.connect(self.gosp)
        self.booking.clicked.connect(self.gobo)
        self.menunorder.clicked.connect(self.goor)
        self.paying.clicked.connect(self.gopa)
        self.contactus.clicked.connect(self.goco)
        self.finish1.clicked.connect(self.gofp1)
        self.backspecial.clicked.connect(self.sp1)
        self.summit.clicked.connect(self.mail)
        self.backorder.clicked.connect(self.sp3)
        self.payingorder.clicked.connect(self.pay)
        self.backpaying.clicked.connect(self.sp4)
        self.finish2.clicked.connect(self.fp2)
        self.backcontact.clicked.connect(self.sp5)
        self.backbooking.clicked.connect(self.sp2)
        self.plus1.clicked.connect(self.p1)
        self.plus2.clicked.connect(self.p2)
        self.plus3.clicked.connect(self.p3)
        self.plus4.clicked.connect(self.p4)
        self.plus5.clicked.connect(self.p5)
        self.plus6.clicked.connect(self.p6)
        self.minus1.clicked.connect(self.m1)
        self.minus2.clicked.connect(self.m2)
        self.minus3.clicked.connect(self.m3)
        self.minus4.clicked.connect(self.m4)
        self.minus5.clicked.connect(self.m5)
        self.minus6.clicked.connect(self.m6)
        self.map.clicked.connect(self.web)
        self.summit.clicked.connect(self.show_popup)
        self._as_counter=0
        self._bm_counter=0
        self._b52_counter=0
        self._beer_counter=0
        self._tq_counter=0
        self._regen_counter=0
          
###link button to page
    def gowhat(self):
        self.stackedWidget.setCurrentIndex(0)
    def gosp(self):
        self.stackedWidget.setCurrentIndex(1)
    def gobo(self):
        self.stackedWidget.setCurrentIndex(2)
    def goor(self):
        self.stackedWidget.setCurrentIndex(3)
    def gopa(self):
        self.stackedWidget.setCurrentIndex(4)
    def goco(self):
        self.stackedWidget.setCurrentIndex(5)
    def gofp1(self):
        self.stackedWidget.setCurrentIndex(6)
    def sp1(self):
        self.stackedWidget.setCurrentIndex(0)
    def sp2(self):
        self.stackedWidget.setCurrentIndex(0)
    def sp3(self):
        self.stackedWidget.setCurrentIndex(0)
    def pay(self):
        self.stackedWidget.setCurrentIndex(4)
    def sp4(self):
        self.stackedWidget.setCurrentIndex(3)
    def fp2(self):
        self.stackedWidget.setCurrentIndex(6)
    def sp5(self):
        self.stackedWidget.setCurrentIndex(0)

##booking Ref Stack Overflow Using PyQt5 for smtp module on python
    def mail(self):
        x = self.email.toPlainText()
        n = self.guest.toPlainText()
        y = self.name.toPlainText()
        z = self.date.toPlainText()
        #send email.
        import smtplib
        email = '63011170@kmitl.ac.th' # My email, you have to set less secure on your gmail first
        password = 'Kongkwan3939' # My password
        message = 'Dear '+y+'''\nDont forget your booking at Drink or Drunk Bar for '''+n+''' guest(s) on '''+z+''' !\n Thankyou for choosing us^^.\n'We hope to see you again''' # The message in the email
        server = smtplib.SMTP('smtp.gmail.com', 587) # Connect to the server
        server.starttls() # Use TLS
        server.login(email, password) # Login to the email server
        server.sendmail(email, x , message) # Send the email
        server.quit() # Logout of the email server
        
###order        
    def p1(self):
        self._as_counter += 1
        self.as200.setText("APEROL SPRIZ "+str(self._as_counter))
        global basket
        basket = basket + 200
        self.showtotal.setText(str(basket)+" THB.")
    
    def p2(self):
        self._bm_counter += 1
        self.bm300.setText("BLOODY MARRY "+str(self._bm_counter))
        global basket
        basket = basket + 300
        self.showtotal.setText(str(basket)+" THB.")
    def p3(self):
        self._b52_counter += 1
        self.b52.setText("B-52 "+str(self._b52_counter))
        global basket
        basket = basket + 150
        self.showtotal.setText(str(basket)+" THB.")
    def p4(self):
        self._beer_counter +=1
        self.beer.setText("BEER "+str(self._beer_counter))
        global basket
        basket = basket + 60
        self.showtotal.setText(str(basket)+" THB.")
    def p5(self):
        self._tq_counter +=1
        self.tq.setText("TEQUILA SUNRISE "+str(self._tq_counter))
        global basket
        basket = basket + 130
        self.showtotal.setText(str(basket)+" THB.")
    def p6(self):
        self._regen_counter +=1
        self.regen.setText("REGENCY "+str(self._regen_counter))
        global basket
        basket = basket + 495
        self.showtotal.setText(str(basket)+" THB.")
    def m1(self):
        self._as_counter -= 1
        self.as200.setText("APEROL SPRIZ "+str(self._as_counter))
        global basket
        basket = basket - 200
        self.showtotal.setText(str(basket)+" THB.")
    def m2(self):
        self._bm_counter -= 1
        self.bm300.setText("BLOODY MARRY "+str(self._bm_counter))
        global basket
        basket = basket - 300
        self.showtotal.setText(str(basket)+" THB.")
    def m3(self):
        self._b52_counter -= 1
        self.b52.setText("B-52 "+str(self._b52_counter))
        global basket
        basket = basket - 150
        self.showtotal.setText(str(basket)+" THB.")
    def m4(self):
        self._beer_counter -= 1
        self.beer.setText("BEER "+str(self._beer_counter))
        global basket
        basket = basket - 60
        self.showtotal.setText(str(basket)+" THB.")
    def m5(self):
        self._tq_counter -= 1
        self.tq.setText("TEQUILA SURISE "+str(self._tq_counter))
        global basket
        basket = basket - 130
        self.showtotal.setText(str(basket)+" THB.")
    def m6(self):
        self._regen_counter -= 1
        self.regen.setText("REGENCY "+str(self._regen_counter))
        global basket
        basket = basket - 495
        self.showtotal.setText(str(basket)+" THB.") 

###map
    def web(self):
        import webbrowser
        webbrowser.open("https://www.google.com/maps?safe=strict&q=kmitl&gs_lcp=CgZwc3ktYWIQARgAMgUILhCTAjICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyCAgAEMcBEK8BMggIABDHARCvAToICAAQsQMQgwE6BQguELEDOgsIABCxAxDHARCjAjoICC4QsQMQgwE6DggAELEDEIMBEMcBEKMCOggIABDHARCjAjoICC4QsQMQkwI6BQgAELEDOgsIABCxAxDHARCvAVCnsgdYx7cHYMS8CWgAcAB4AYAB5wKIAawIkgEHMC4zLjAuMpgBAKABAaoBB2d3cy13aXo&um=1&ie=UTF-8&sa=X&ved=2ahUKEwjQ96S2xsbtAhXY73MBHUQcCWoQ_AUoAXoECAoQAw")
###showpopup
    def show_popup(self):
        msg= QMessageBox()
        msg.setWindowTitle("YOUR RESERVATION :) ")
        msg.setText("You have alredy made a reservation🎉. 💌Please check your email!. 🎄 Enjoy your day.🎅🏻")
        k = msg.exec_()
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DRINK OR DRUNK"))
        self.specialevent.setText(_translate("Form", " SPECIAL EVENT"))
        self.booking.setText(_translate("Form", "BOOKING"))
        self.menunorder.setText(_translate("Form", "MENU n ORDER"))
        self.paying.setText(_translate("Form", "PAYING"))
        self.map.setText(_translate("Form", "MAP"))
        self.contactus.setText(_translate("Form", "CONTACT US"))
        self.finish1.setText(_translate("Form", "FINISH"))
        self.backspecial.setText(_translate("Form", "BACK"))
        self.summit.setText(_translate("Form", "SUMMIT"))
        self.backbooking.setText(_translate("Form", "BACK"))
        self.minus1.setText(_translate("Form", "-"))
        self.minus4.setText(_translate("Form", "-"))
        self.minus3.setText(_translate("Form", "-"))
        self.minus2.setText(_translate("Form", "-"))
        self.plus4.setText(_translate("Form", "+"))
        self.plus5.setText(_translate("Form", "+"))
        self.plus1.setText(_translate("Form", "+"))
        self.plus6.setText(_translate("Form", "+"))
        self.backorder.setText(_translate("Form", "BACK"))
        self.plus3.setText(_translate("Form", "+"))
        self.minus6.setText(_translate("Form", "-"))
        self.minus5.setText(_translate("Form", "-"))
        self.plus2.setText(_translate("Form", "+"))
        self.payingorder.setText(_translate("Form", "PAYING"))
        self.backpaying.setText(_translate("Form", "BACK"))
        self.finish2.setText(_translate("Form", "FINISH"))
        self.backcontact.setText(_translate("Form", "BACK"))
        self.start.setText(_translate("Form", "START"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
