# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drinkordrunk.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setMinimumSize(QtCore.QSize(502, 501))
        Form.setMaximumSize(QtCore.QSize(502, 501))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pic/beeremo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.drinkordrunk = QtWidgets.QStackedWidget(Form)
        self.drinkordrunk.setGeometry(QtCore.QRect(0, 0, 501, 511))
        self.drinkordrunk.setObjectName("drinkordrunk")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 501, 491))
        self.label_2.setMinimumSize(QtCore.QSize(461, 401))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../pic/IMG_1373[7167].jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.specialevent = QtWidgets.QPushButton(self.widget)
        self.specialevent.setGeometry(QtCore.QRect(40, 150, 201, 41))
        self.specialevent.setStyleSheet("QPushButton{\n"
"font: 22pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.specialevent.setObjectName("specialevent")
        self.booking = QtWidgets.QPushButton(self.widget)
        self.booking.setGeometry(QtCore.QRect(290, 150, 131, 41))
        self.booking.setStyleSheet("QPushButton{\n"
"font: 22pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.booking.setObjectName("booking")
        self.menunorder = QtWidgets.QPushButton(self.widget)
        self.menunorder.setGeometry(QtCore.QRect(40, 240, 191, 41))
        self.menunorder.setStyleSheet("QPushButton{\n"
"font: 22pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.menunorder.setObjectName("menunorder")
        self.paying = QtWidgets.QPushButton(self.widget)
        self.paying.setGeometry(QtCore.QRect(290, 240, 131, 41))
        self.paying.setStyleSheet("QPushButton{\n"
"font: 22pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"")
        self.paying.setObjectName("paying")
        self.map = QtWidgets.QPushButton(self.widget)
        self.map.setGeometry(QtCore.QRect(70, 320, 131, 41))
        self.map.setStyleSheet("QPushButton{\n"
"font: 22pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.map.setObjectName("map")
        self.contactus = QtWidgets.QPushButton(self.widget)
        self.contactus.setGeometry(QtCore.QRect(270, 320, 171, 41))
        self.contactus.setStyleSheet("QPushButton{\n"
"font: 22pt \"Comic Sans MS\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.contactus.setObjectName("contactus")
        self.finish1 = QtWidgets.QPushButton(self.widget)
        self.finish1.setGeometry(QtCore.QRect(190, 390, 91, 41))
        self.finish1.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.finish1.setObjectName("finish1")
        self.drinkordrunk.addWidget(self.widget)
        self.specialeventpage = QtWidgets.QWidget()
        self.specialeventpage.setObjectName("specialeventpage")
        self.label_3 = QtWidgets.QLabel(self.specialeventpage)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 501, 491))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../pic/IMG_1375[7175].jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.backspecial = QtWidgets.QPushButton(self.specialeventpage)
        self.backspecial.setGeometry(QtCore.QRect(210, 440, 101, 31))
        self.backspecial.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 22pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backspecial.setObjectName("backspecial")
        self.drinkordrunk.addWidget(self.specialeventpage)
        self.bookingpage = QtWidgets.QWidget()
        self.bookingpage.setObjectName("bookingpage")
        self.label_4 = QtWidgets.QLabel(self.bookingpage)
        self.label_4.setGeometry(QtCore.QRect(0, -10, 501, 521))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../pic/IMG_1388[7195].jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QTextEdit(self.bookingpage)
        self.name.setGeometry(QtCore.QRect(240, 170, 181, 21))
        self.name.setObjectName("name")
        self.email = QtWidgets.QTextEdit(self.bookingpage)
        self.email.setGeometry(QtCore.QRect(240, 230, 181, 21))
        self.email.setObjectName("email")
        self.tel = QtWidgets.QTextEdit(self.bookingpage)
        self.tel.setGeometry(QtCore.QRect(240, 310, 181, 21))
        self.tel.setObjectName("tel")
        self.guest = QtWidgets.QTextEdit(self.bookingpage)
        self.guest.setGeometry(QtCore.QRect(240, 390, 181, 21))
        self.guest.setObjectName("guest")
        self.date = QtWidgets.QTextEdit(self.bookingpage)
        self.date.setGeometry(QtCore.QRect(240, 450, 181, 21))
        self.date.setObjectName("date")
        self.backbooking = QtWidgets.QPushButton(self.bookingpage)
        self.backbooking.setGeometry(QtCore.QRect(410, 480, 81, 16))
        self.backbooking.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backbooking.setObjectName("backbooking")
        self.drinkordrunk.addWidget(self.bookingpage)
        self.orderpage = QtWidgets.QWidget()
        self.orderpage.setObjectName("orderpage")
        self.label_5 = QtWidgets.QLabel(self.orderpage)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../pic/IMG_1391[7210].jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.minus1 = QtWidgets.QPushButton(self.orderpage)
        self.minus1.setGeometry(QtCore.QRect(70, 180, 16, 16))
        self.minus1.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus1.setObjectName("minus1")
        self.minus4 = QtWidgets.QPushButton(self.orderpage)
        self.minus4.setGeometry(QtCore.QRect(180, 310, 16, 16))
        self.minus4.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus4.setObjectName("minus4")
        self.minus3 = QtWidgets.QPushButton(self.orderpage)
        self.minus3.setGeometry(QtCore.QRect(70, 310, 16, 16))
        self.minus3.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus3.setObjectName("minus3")
        self.minus2 = QtWidgets.QPushButton(self.orderpage)
        self.minus2.setGeometry(QtCore.QRect(180, 180, 16, 16))
        self.minus2.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus2.setObjectName("minus2")
        self.plus4 = QtWidgets.QPushButton(self.orderpage)
        self.plus4.setGeometry(QtCore.QRect(150, 310, 16, 16))
        self.plus4.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus4.setObjectName("plus4")
        self.plus5 = QtWidgets.QPushButton(self.orderpage)
        self.plus5.setGeometry(QtCore.QRect(50, 450, 16, 16))
        self.plus5.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus5.setObjectName("plus5")
        self.plus1 = QtWidgets.QPushButton(self.orderpage)
        self.plus1.setGeometry(QtCore.QRect(50, 180, 16, 16))
        self.plus1.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus1.setObjectName("plus1")
        self.showorder = QtWidgets.QLabel(self.orderpage)
        self.showorder.setGeometry(QtCore.QRect(280, 140, 151, 241))
        self.showorder.setObjectName("showorder")
        self.plus6 = QtWidgets.QPushButton(self.orderpage)
        self.plus6.setGeometry(QtCore.QRect(150, 450, 16, 16))
        self.plus6.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus6.setObjectName("plus6")
        self.backorder = QtWidgets.QPushButton(self.orderpage)
        self.backorder.setGeometry(QtCore.QRect(250, 440, 101, 41))
        self.backorder.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 22pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backorder.setObjectName("backorder")
        self.plus3 = QtWidgets.QPushButton(self.orderpage)
        self.plus3.setGeometry(QtCore.QRect(50, 310, 16, 16))
        self.plus3.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus3.setObjectName("plus3")
        self.minus6 = QtWidgets.QPushButton(self.orderpage)
        self.minus6.setGeometry(QtCore.QRect(180, 450, 16, 16))
        self.minus6.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus6.setObjectName("minus6")
        self.minus5 = QtWidgets.QPushButton(self.orderpage)
        self.minus5.setGeometry(QtCore.QRect(70, 450, 16, 16))
        self.minus5.setStyleSheet("QPushButton{\n"
"font: 12pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.minus5.setObjectName("minus5")
        self.showtotal = QtWidgets.QLabel(self.orderpage)
        self.showtotal.setGeometry(QtCore.QRect(270, 400, 201, 21))
        self.showtotal.setObjectName("showtotal")
        self.plus2 = QtWidgets.QPushButton(self.orderpage)
        self.plus2.setGeometry(QtCore.QRect(150, 180, 16, 16))
        self.plus2.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.plus2.setObjectName("plus2")
        self.payingorder = QtWidgets.QPushButton(self.orderpage)
        self.payingorder.setGeometry(QtCore.QRect(360, 440, 111, 41))
        self.payingorder.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 22pt \"Elephant\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 127);\n"
"background-color: rgb(254, 228, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 207, 251);\n"
"}")
        self.payingorder.setObjectName("payingorder")
        self.drinkordrunk.addWidget(self.orderpage)
        self.payingpage = QtWidgets.QWidget()
        self.payingpage.setObjectName("payingpage")
        self.label_6 = QtWidgets.QLabel(self.payingpage)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../pic/IMG_1390[7206].jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.backpaying = QtWidgets.QPushButton(self.payingpage)
        self.backpaying.setGeometry(QtCore.QRect(20, 420, 91, 41))
        self.backpaying.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backpaying.setObjectName("backpaying")
        self.finish2 = QtWidgets.QPushButton(self.payingpage)
        self.finish2.setGeometry(QtCore.QRect(390, 420, 91, 41))
        self.finish2.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.finish2.setObjectName("finish2")
        self.drinkordrunk.addWidget(self.payingpage)
        self.contactpage = QtWidgets.QWidget()
        self.contactpage.setObjectName("contactpage")
        self.label_7 = QtWidgets.QLabel(self.contactpage)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../pic/ct.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.backcontact = QtWidgets.QPushButton(self.contactpage)
        self.backcontact.setGeometry(QtCore.QRect(190, 430, 101, 31))
        self.backcontact.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"font: 22pt \"Elephant\";\n"
"background-color: rgb(6, 74, 147);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.backcontact.setObjectName("backcontact")
        self.drinkordrunk.addWidget(self.contactpage)
        self.firstpage = QtWidgets.QWidget()
        self.firstpage.setObjectName("firstpage")
        self.label = QtWidgets.QLabel(self.firstpage)
        self.label.setGeometry(QtCore.QRect(-10, 0, 521, 511))
        self.label.setMaximumSize(QtCore.QSize(1024, 768))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../pic/IMG_1377[7179].jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(self.firstpage)
        self.start.setGeometry(QtCore.QRect(170, 390, 151, 31))
        self.start.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"font: 22pt \"Elephant\";\n"
"background-color: rgb(0, 0, 127);\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 255, 255);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.start.setObjectName("start")
        self.drinkordrunk.addWidget(self.firstpage)

        self.retranslateUi(Form)
        self.drinkordrunk.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DRINK OR DRUNK"))
        self.specialevent.setText(_translate("Form", " SPECIAL EVENT"))
        self.booking.setText(_translate("Form", "BOOKING"))
        self.menunorder.setText(_translate("Form", "MENU n ORDER"))
        self.paying.setText(_translate("Form", "PAYING"))
        self.map.setText(_translate("Form", "MAP"))
        self.contactus.setText(_translate("Form", "CONTACT US"))
        self.finish1.setText(_translate("Form", "FINISH"))
        self.backspecial.setText(_translate("Form", "BACK"))
        self.backbooking.setText(_translate("Form", "DONE"))
        self.minus1.setText(_translate("Form", "-"))
        self.minus4.setText(_translate("Form", "-"))
        self.minus3.setText(_translate("Form", "-"))
        self.minus2.setText(_translate("Form", "-"))
        self.plus4.setText(_translate("Form", "+"))
        self.plus5.setText(_translate("Form", "+"))
        self.plus1.setText(_translate("Form", "+"))
        self.showorder.setText(_translate("Form", "order"))
        self.plus6.setText(_translate("Form", "+"))
        self.backorder.setText(_translate("Form", "BACK"))
        self.plus3.setText(_translate("Form", "+"))
        self.minus6.setText(_translate("Form", "-"))
        self.minus5.setText(_translate("Form", "-"))
        self.showtotal.setText(_translate("Form", "total"))
        self.plus2.setText(_translate("Form", "+"))
        self.payingorder.setText(_translate("Form", "PAYING"))
        self.backpaying.setText(_translate("Form", "BACK"))
        self.finish2.setText(_translate("Form", "FINISH"))
        self.backcontact.setText(_translate("Form", "BACK"))
        self.start.setText(_translate("Form", "START"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


